### PR TITLE
revert Register Advance Settings, Data Source management,Index Pattern management and SavedObject management as standalone app, retire dashboard management 

### PR DESCRIPTION
**Pull request by ruanyl**
### Description

Revert Register Advance Settings, Data Source management,Index Pattern management and SavedObject management as standalone app, retire dashboard management #208

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by SuZhou-Joe** [comment]
LGTM, let's wait for CI to pass.

**Review by raintygao — APPROVED** [review]

**Review by Hailong-am — APPROVED** [review]

**Comment by Hailong-am** [comment]
seems that few cases are failed.

**Comment by ruanyl** [comment]
> seems that few cases are failed.

Seems due to the path changes of the cypress tests in FTR

**Comment by ruanyl** [comment]
@Hailong-am run it manually against ftr `main`, the test cases passed https://github.com/ruanyl/OpenSearch-Dashboards/actions/runs/8181890144/job/22372367328

**Comment by Hailong-am** [comment]
> > seems that few cases are failed.
> 
> Seems due to the app path changes of the cypress tests in FTR

do we need to 

> > seems that few cases are failed.
> 
> Seems due to the app path changes of the cypress tests in FTR

@ruanyl should we change the branch back to main here https://github.com/ruanyl/OpenSearch-Dashboards/blob/workspace-pr-integr/.github/workflows/cypress_workflow.yml#L31C72-L31C81

**Comment by ruanyl** [comment]
changed to `main`, the tests passed now

**Pull request merged**
