### PR TITLE
disable github workflows running on windows for development

### PR DESCRIPTION
**Pull request by ruanyl**
the jobs for windows are queued forever, disable it for development

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by Hailong-am — APPROVED** [review]

**Comment by Hailong-am** [comment]
I have disabled Changelog workflow 
image

**Comment by Hailong-am** [comment]
[cypress test](https://github.com/ruanyl/OpenSearch-Dashboards/blob/disable-workflow-for-windows/.github/workflows/cypress_workflow.yml#L22) still run on `ubuntu-latest`, should we change to self host runner? does there has any limitation @suzhou-joe

**Comment by ruanyl** [comment]
> [cypress test](https://github.com/ruanyl/OpenSearch-Dashboards/blob/disable-workflow-for-windows/.github/workflows/cypress_workflow.yml#L22) still run on `ubuntu-latest`, should we change to self host runner? does there has any limitation @SuZhou-Joe

It seems self-hosted runner doesn't not support docker

**Comment by SuZhou-Joe** [comment]
> > [cypress test](https://github.com/ruanyl/OpenSearch-Dashboards/blob/disable-workflow-for-windows/.github/workflows/cypress_workflow.yml#L22) still run on `ubuntu-latest`, should we change to self host runner? does there has any limitation @SuZhou-Joe
> 
> It seems self-hosted runner does not support docker

Yeah, docker in not enable in default container mode, and I think we could skip cypress test for now until we find a way to run docker in self-hosted runner.

**Comment by ruanyl** [comment]
@SuZhou-Joe good point, disabled cypress test for now. I will merge this PR

**Pull request merged**
