### PR TITLE
fix failed tests after syncing with main

### PR DESCRIPTION
**Pull request by ruanyl**
### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by yuye-aws — APPROVED** [review]

**Review by wanglam — APPROVED** [review]

**Comment by wanglam** [comment]
@ruanyl The main branch may have some different snapshots with 2.9 branch. Do we need to do the automatic backport?

**Comment by ruanyl** [comment]
> @ruanyl The main branch may have some different snapshots with 2.9 branch. Do we need to do the automatic backport?

@wanglam You mean those changes are in main but not in 2.9?

**Comment by wanglam** [comment]
> > @ruanyl The main branch may have some different snapshots with 2.9 branch. Do we need to do the automatic backport?
> 
> @wanglam You mean those changes are in main but not in 2.9?

Yes. Will these be an issue?

**Comment by ruanyl** [comment]
> > > @ruanyl The main branch may have some different snapshots with 2.9 branch. Do we need to do the automatic backport?
> > 
> > 
> > @wanglam You mean those changes are in main but not in 2.9?
> 
> Yes. Will these be an issue?

Right, that will be an issue, I will remove the backport tag.

**Review by raintygao — APPROVED** [review]

**Pull request merged**
